name: Unzip File
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: unzip lms.zip && rm lms.zip
      - run: git add . && git commit -m "Unzipped files" && git push
